app:
  name: "match"
  version: "1.0.0"

http:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

postgres:
  host: "localhost"
  user: "postgres"
  password: "postgres"
  port: 5432
  database: "postgres"