version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: match-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: match
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/mongo-init-scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - match-network

  # Веб-приложение lkshmatch
  #  lkshmatch-web:
  #    build: .
  #    container_name: lkshmatch-web
  #    restart: unless-stopped
  #    ports:
  #      - "8000:8000"
  #    environment:
  #      - MATCH_ENV=prod
  #      - MATCH_CORE_HOST=127.0.0.1
  #      - MATCH_CORE_PORT=32442
  #      - MATCH_TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
  #      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/lkshmatch?authSource=admin
  #    depends_on:
  #      - mongodb
  #    networks:
  #      - lkshmatch-network
  #    volumes:
  #      - ./config.toml:/app/bff/config.toml:ro

  # Telegram бот (опционально, можно запускать отдельно)
  match-bot:
    build: .
    container_name: match-bot
    restart: unless-stopped
    environment:
      - MATCH_ENV=prod
      - MATCH_CORE_HOST=127.0.0.1
      - MATCH_CORE_PORT=32442
      - MATCH_TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - MONGODB_URL=mongodb://admin:password123@mongodb:27017/match?authSource=admin
    depends_on:
      - mongodb
    networks:
      - match-network
    volumes:
      - ./config.toml:/app/bff/config.toml:ro
    command: [ "python", "-m", "lkshmatch.main" ]

volumes:
  mongodb_data:
    driver: local

networks:
  match-network:
    driver: bridge