/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SportSectionList } from '../../models/sport-section-list';

export interface CoreSportListGet$Params {
}

export function coreSportListGet(http: HttpClient, rootUrl: string, params?: CoreSportListGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'sports_sections': SportSectionList;
}>> {
  const rb = new RequestBuilder(rootUrl, coreSportListGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'sports_sections': SportSectionList;
      }>;
    })
  );
}

coreSportListGet.PATH = '/core/sport/list';
