/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Activity } from './models/activity';
export type { ActivityEnrollPlayerRequest } from './models/activity-enroll-player-request';
export type { CreateActivityRequest } from './models/create-activity-request';
export type { Player } from './models/player';
export type { PlayerList } from './models/player-list';
export type { RegisterPlayerRequest } from './models/register-player-request';
export type { SportSection } from './models/sport-section';
export type { SportSectionList } from './models/sport-section-list';
export type { Team } from './models/team';
export type { TeamList } from './models/team-list';
export type { UpdateActivityRequest } from './models/update-activity-request';
