/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { coreSportListGet } from '../fn/sport-sections/core-sport-list-get';
import { CoreSportListGet$Params } from '../fn/sport-sections/core-sport-list-get';
import { SportSectionList } from '../models/sport-section-list';

@Injectable({ providedIn: 'root' })
export class SportSectionsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `coreSportListGet()` */
  static readonly CoreSportListGetPath = '/core/sport/list';

  /**
   * Возвращает список всех существующих видов спорта.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `coreSportListGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  coreSportListGet$Response(params?: CoreSportListGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'sports_sections': SportSectionList;
}>> {
    return coreSportListGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Возвращает список всех существующих видов спорта.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `coreSportListGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  coreSportListGet(params?: CoreSportListGet$Params, context?: HttpContext): Observable<{
'sports_sections': SportSectionList;
}> {
    return this.coreSportListGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
'sports_sections': SportSectionList;
}>): {
'sports_sections': SportSectionList;
} => r.body)
    );
  }

}
