services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: prod.dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/api/
    networks:
      - api
    env_file:
      - .env
