services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/api/
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PORT: ${DB_POSTGRES_PORT}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
    networks:
      - backend
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_app
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'qwerty'
    ports:
      - "5050:80"


networks:
  backend:
    driver: "bridge"
