services:
  tests:
    container_name: tests
    build:
      context: .
      dockerfile: test.dockerfile
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PORT: ${DB_POSTGRES_PORT}
      POSTGRES_DB: ${DB_POSTGRES_NAME}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASS}
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
