services:
  match-app:
    container_name: match-core
    build:
      context: ..
      dockerfile: core/dev.dockerfile
    ports:
      - '8080:8080'
    environment:
      APP_POSTGRES_HOST: "postgres"
      APP_POSTGRES_NAME: ${POSTGRES_USER}
      APP_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_POSTGRES_PORT: 5432
      APP_POSTGRES_DATABASE: ${POSTGRES_DB}
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - default
      - match-shared-network

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_EXPOSED_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  match-shared-network:
    driver: bridge
    name: match-shared-network