services:
  tests:
    container_name: tests
    build:
      context: .
      dockerfile: test.dockerfile
    networks:
      - backend_test
    env_file:
      - .env.test
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - backend_test
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_app
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'qwerty'
    ports:
      - "5050:80"


networks:
  backend_test:
    driver: "bridge"
