services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/api/
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
