services:
  tests:
    container_name: tests
    build:
      context: ..
      dockerfile: core/test.dockerfile
    environment:
      APP_POSTGRES_HOST: ${POSTGRES_HOST}
      APP_POSTGRES_USER: ${POSTGRES_USER}
      APP_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_POSTGRES_PORT: ${POSTGRES_PORT}
      APP_POSTGRES_DATABASE: ${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16.3
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    command:
      - -p ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}' ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
