/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Player } from '../../models/player';

export interface CorePlayerByTgGet$Params {
  tg_id?: number;
  tg_username?: string;
}

export function corePlayerByTgGet(http: HttpClient, rootUrl: string, params?: CorePlayerByTgGet$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'player': Player;
}>> {
  const rb = new RequestBuilder(rootUrl, corePlayerByTgGet.PATH, 'get');
  if (params) {
    rb.query('tg_id', params.tg_id, {});
    rb.query('tg_username', params.tg_username, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'player': Player;
      }>;
    })
  );
}

corePlayerByTgGet.PATH = '/core/player/by_tg';
