/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Player } from '../models/player';
export interface Activity {
  creator: Player;
  description?: string;

  /**
   * Идентификатор активности
   */
  id: number;
  title: string;
}
