/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateActivityRequest {

  /**
   * Core-идентификатор создателя активности
   */
  creator_id: number;

  /**
   * Описание активности
   */
  description?: string;
  sport_section_id: number;

  /**
   * Название активности
   */
  title: string;
}
