/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Структура описывающая пользователя
 */
export interface Player {
  core_id: number;
  name: string;
  tg_id: number;
  tg_username: string;
}
