/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SportSection } from '../models/sport-section';
export type SportSectionList = Array<SportSection>;
