/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Player } from '../models/player';
import { PlayerList } from '../models/player-list';

/**
 * Команда с игроками
 */
export interface Team {
  captain: Player;
  id: number;
  members: PlayerList;
  name: string;
}
