/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateActivityRequest {

  /**
   * Описание активности
   */
  description: string;

  /**
   * Название активности
   */
  title: string;
}
