/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActivityEnrollPlayerRequest } from '../../models/activity-enroll-player-request';
import { Team } from '../../models/team';

export interface CoreActivityIdEnrollPost$Params {
  id: number;
      body: ActivityEnrollPlayerRequest
}

export function coreActivityIdEnrollPost(http: HttpClient, rootUrl: string, params: CoreActivityIdEnrollPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'team': Team;
}>> {
  const rb = new RequestBuilder(rootUrl, coreActivityIdEnrollPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'team': Team;
      }>;
    })
  );
}

coreActivityIdEnrollPost.PATH = '/core/activity/{id}/enroll';
