/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Activity } from '../../models/activity';

export interface CoreActivityDeleteByIdPost$Params {
  id: number;
  'Privilege-Token': string;
}

export function coreActivityDeleteByIdPost(http: HttpClient, rootUrl: string, params: CoreActivityDeleteByIdPost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'activity': Activity;
}>> {
  const rb = new RequestBuilder(rootUrl, coreActivityDeleteByIdPost.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('Privilege-Token', params['Privilege-Token'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'activity': Activity;
      }>;
    })
  );
}

coreActivityDeleteByIdPost.PATH = '/core/activity/delete_by/{id}';
