/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Activity } from '../../models/activity';
import { CreateActivityRequest } from '../../models/create-activity-request';

export interface CoreActivityCreatePost$Params {
  'Privilege-Token': string;
      body: CreateActivityRequest
}

export function coreActivityCreatePost(http: HttpClient, rootUrl: string, params: CoreActivityCreatePost$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'activity': Activity;
}>> {
  const rb = new RequestBuilder(rootUrl, coreActivityCreatePost.PATH, 'post');
  if (params) {
    rb.header('Privilege-Token', params['Privilege-Token'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'activity': Activity;
      }>;
    })
  );
}

coreActivityCreatePost.PATH = '/core/activity/create';
