app:
  name: "match"
  version: "1.0.0"

http:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

database:
  name: "example"
  password: <placeholder>
  port: 22
  username: "example"
  host: "1.1.1.1"

web:
  host: "1.1.1.1"
  password: <placeholder>
  port: 22

tg:
  token: <placeholder>