app:
  name: "match"
  version: "1.0.0"

http:
  port: 8080
  read_timeout: 10s
  write_timeout: 10s
  shutdown_timeout: 5s

postgres:
  host: "localhost"
  name: "postgres"
  password: "postgres"
  port: 5432
  db: "postgres"

web:
  host: "1.1.1.1"
  password: <placeholder>
  port: 22

tg:
  token: <placeholder>
