openapi: 3.0.0
info:
  title: Core
  description: Client for app core part
  version: 1.0.0
paths:
  /core/tournament/create:
    post:
      operationId: createTournament
      summary: "Создает турнир"
      parameters:
        - name: sport
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: registration_deadline
          in: query
          required: true
          schema:
            type: string
            format: date-time

        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date-time
      responses:
        "201":
          $ref: '#/components/responses/TournamentCreationResponse'
        "400":
          $ref: '#/components/responses/ErrorResponse'
        "409":
          $ref: '#/components/responses/ErrorResponse'

  /core/player/register:
    get:
      operationId: registerPlayer
      summary: "Регистрирует пользователя"
      parameters:
        - name: tg_username
          in: query
          required: true
          schema:
            type: string
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: tg_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          $ref: '#/components/responses/ErrorResponse'
        "201":
          $ref: '#/components/responses/PlayerRegistrationResponse'
        "400":
          $ref: '#/components/responses/ErrorResponse'

  /core/sports/get:
    get:
      summary: "Возращает список всех возможных существующих видов спорта"
      responses:
        "200":
          $ref: '#/components/responses/SportSectionList'

  /core/sport/get/{sport}:
    get:
      summary: "Возвращает для определенного спорта массив пользователей, которые участвуют в данном виде спорта"
      parameters:
        - name: sport
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: '#/components/responses/SportSectionPlayers'
  /core/sports/get/all:
    get:
      summary: "Возвращает словаль, где для каждого существующего вида спорта соотносится массив пользователей"
      responses:
        "200":
          $ref: '#/components/responses/SportSectionPlayers'

components:
  schemas:
    Player:
      description: "Структура описывающая пользователя"
      type: object
      properties:
        tgId:
          type: integer
          format: int64
        coreId:
          type: integer
          format: int64
    PlayerList:
      type: array
      items:
        $ref: "#/components/schemas/Player"


    PlayersBySport:
      description: "Словарь из вида спорта в массив пользователей, которые на него записаны"
      type: object
      additionalProperties:
        $ref: "#/components/schemas/PlayerList"


  responses:
    TournamentCreationResponse:
      content:
        application/json:
          schema:
            type: "object"
            properties:
              id:
                type: integer
                format: int64
                description: Идентификатор турнира
      description: ""
    PlayerRegistrationResponse:
      description: "Информация о регистрации пользователя"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              id:
                type: integer
                format: int64
                description: Core-идентификатор

    SportSectionPlayers:
      description: "Словарь где ключ это вид спорта а значение это масиив id игроков которые принимают участие в данном виде спорта"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PlayersBySport"


    SportSectionList:
      description: "Массив, в котором содержатся названия всех существующих видов спорта"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              sports_sections:
                type: array
                items:
                  type: string

    ErrorResponse:
      content:
        application/json:
          schema:
            type: "object"
            required:
              - message
            properties:
              message:
                type: string
      description: ""




