openapi: 3.0.0
info:
  title: Test
  description: Test
  version: 1.0.0
paths:
  /core/player/register:
    get:
      operationId: registerPlayer
      summary: "Регистрирует пользователя"
      parameters:
        - name: tg_username
          in: query
          required: true
          schema:
            type: string
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: tg_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          $ref: '#/components/responses/ErrorResponse'
        201:
          $ref: '#/components/responses/PlayerRegistrationResponse'
        400:
          $ref: '#/components/responses/ErrorResponse'

components:
  responses:
    PlayerRegistrationResponse:
      content:
        application/json:
          schema:
            type: "object"
            properties:
              id:
                type: integer
                format: int64
                description: Core-идентификатор
      description: ""
    ErrorResponse:
      content:
        application/json:
          schema:
            type: "object"
            required:
              - message
            properties:
              message:
                type: string
      description: ""




