name: check

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          working-directory: path/to/your/subproject
