name: check

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - core-set-ci

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          working-directory: core
